#!/bin/bash

down()
{
	local DOWN="/etc/nginx/down.sh"

	if [ -f $DOWN ]
    then
    	 chmod +x $DOWN && chmod 755 $DOWN && eval $DOWN;
    fi

    exit
}

trap down SIGTERM

exec /usr/sbin/nginx > /dev/null 2>&1